import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useCrowd } from '../context/CrowdContext';
import { LiveCrowdMeter } from '../components/crowd/LiveCrowdMeter';
import { ZoneCongestionMap } from '../components/crowd/ZoneCongestionMap';
import { SimulatedCCTVStream } from '../components/crowd/SimulatedCCTVStream';
import { MetricCard } from '../components/common/MetricCard';
import {
  Activity,
  Users,
  Clock,
  AlertTriangle,
  Flame,
  Radio,
  RefreshCw,
  Sparkles,
  ShieldCheck,
  TrendingUp,
  MapPin,
  Eye,
  ArrowRight,
  ArrowDownRight,
  ArrowUpRight,
  Info,
} from 'lucide-react';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';
import { Link } from 'react-router-dom';

export const LiveCrowdPage = () => {
  const { t } = useTranslation();
  const { crowdData, temples, lastUpdated, triggerSimulationPulse, isSimulating } = useCrowd();
  const [selectedTempleId, setSelectedTempleId] = useState('somnath');

  const selectedTemple = temples.find((t) => t.id === selectedTempleId) || temples[0];
  const activeOverview = crowdData?.templeOverview?.find((t) => t.templeId === selectedTempleId);

  return (
    <div className="min-h-screen bg-[#F8F5EF] py-10 sm:py-16 pb-24 space-y-10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-[#EBE4D5]">
          <div>
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#E97820]">
              <Radio className="w-4 h-4 animate-pulse text-red-500" />
              <span>Simulation / Demo Telemetry</span>
            </div>
            <h1 className="font-serif text-3xl sm:text-4xl font-bold text-[#102A56] mt-1">
              Live Crowd Intelligence Hub
            </h1>
            <p className="text-xs sm:text-sm text-slate-600">
              Real-time simulated crowd telemetry across Somnath, Dwarka, Ambaji, and Pavagadh. Updates dynamically every 6-8 seconds.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div className="text-right text-xs text-slate-500 hidden sm:block">
              <span>Simulation Node:</span>
              <strong className="block text-[#102A56]">{new Date(lastUpdated).toLocaleTimeString()}</strong>
            </div>

            <button
              onClick={triggerSimulationPulse}
              disabled={isSimulating}
              className="px-4 py-2.5 rounded-xl bg-[#102A56] hover:bg-[#1B3B74] text-white text-xs font-bold flex items-center gap-2 shadow-md disabled:opacity-50 transition-all"
            >
              <RefreshCw className={`w-3.5 h-3.5 text-[#D5A63A] ${isSimulating ? 'animate-spin' : ''}`} />
              <span>Simulate Pulse</span>
            </button>
          </div>
        </div>

        {/* Telemetry Notice Banner */}
        <div className="p-3.5 rounded-2xl bg-amber-50/80 border border-amber-200/80 text-xs text-amber-900 flex items-center justify-between gap-3 shadow-sm">
          <div className="flex items-center gap-2">
            <Info className="w-4 h-4 text-[#E97820] shrink-0" />
            <span>
              <strong>Simulation / Demo Telemetry:</strong> Metrics and queue simulations are dynamically generated by DivYatra AI Engine for operational demonstration. Architecture is pre-configured for future Python/OpenCV/YOLO edge inference integration.
            </span>
          </div>
          <span className="text-[10.5px] font-bold uppercase px-2.5 py-0.5 rounded-full bg-amber-200/60 text-amber-900 shrink-0">
            Demo Mode Active
          </span>
        </div>

        {/* Top 4 Real-time Metric Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          <MetricCard
            title="Active Pilgrims in Shrines"
            value={crowdData?.totalActivePilgrims ? crowdData.totalActivePilgrims.toLocaleString() : "15,620"}
            subtitle="Combined concurrent count"
            icon={Users}
            color="navy"
            trend="up"
            trendValue="+3.2%"
          />

          <MetricCard
            title="Average Sanctum Wait"
            value={`${crowdData?.averageWaitTimeMinutes || 34} Mins`}
            subtitle="Across all 4 target shrines"
            icon={Clock}
            color="saffron"
            trend="down"
            trendValue="-4 mins"
          />

          <MetricCard
            title="Critical Watch Zones"
            value={crowdData?.activeCriticalZones || 2}
            subtitle="Corridors under AI guidance"
            icon={AlertTriangle}
            color="white"
            badge="Monitored"
          />

          <MetricCard
            title="System Alert Status"
            value={crowdData?.systemAlertLevel || "ELEVATED_WATCH"}
            subtitle="Active congestion surveillance"
            icon={ShieldCheck}
            color="white"
            badge="Verified"
          />
        </div>

        {/* Shrine Selector Tabs */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-1.5 sm:gap-2 p-1.5 rounded-2xl bg-white border border-[#E5DED0] shadow-sm">
          {temples.map((tTemple) => {
            const isSelected = selectedTempleId === tTemple.id;
            const overview = crowdData?.templeOverview?.find((o) => o.templeId === tTemple.id);
            const tabName = t(`templeData.${tTemple.id}.shortName`, { defaultValue: tTemple.shortName || tTemple.name });
            return (
              <button
                key={tTemple.id}
                onClick={() => setSelectedTempleId(tTemple.id)}
                className={`py-2.5 sm:py-3 px-2 sm:px-4 rounded-xl text-xs font-bold transition-all flex items-center justify-between gap-1.5 min-h-[44px] ${
                  isSelected
                    ? 'bg-[#102A56] text-white shadow-md'
                    : 'text-slate-700 hover:bg-[#FAF8F5]'
                }`}
              >
                <span className="truncate">{tabName}</span>
                <span className={`px-1.5 sm:px-2 py-0.5 rounded-full text-[10px] font-mono shrink-0 ${
                  isSelected ? 'bg-[#E97820] text-white' : 'bg-gray-100 text-gray-700'
                }`}>
                  {overview?.crowdPercentage || tTemple.liveStatus?.crowdPercentage || 50}%
                </span>
              </button>
            );
          })}
        </div>

        {/* Featured Live Meter for Selected Temple */}
        {selectedTemple && (
          <div className="space-y-4 sm:space-y-6">
            <LiveCrowdMeter
              percentage={activeOverview?.crowdPercentage || selectedTemple.liveStatus?.crowdPercentage || 50}
              waitMinutes={activeOverview?.avgWait || selectedTemple.liveStatus?.estimatedWaitMinutes || 25}
              activeCount={activeOverview?.activeCount || selectedTemple.liveStatus?.activePilgrimsInPremise || 3500}
              templeName={selectedTemple.name}
              statusLabel={activeOverview?.statusLabel || selectedTemple.liveStatus?.statusLabel || "Optimal Flow"}
            />

            {/* Inflow / Outflow & Predictive Trend Strip */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4">
              <div className="p-3.5 sm:p-4 rounded-2xl bg-white border border-[#E5DED0] shadow-sm space-y-1">
                <span className="text-[10px] sm:text-[11px] text-gray-500 font-semibold block uppercase">Turnstile Inflow / Outflow</span>
                <div className="flex items-center gap-3 sm:gap-4 text-xs font-bold">
                  <span className="text-emerald-700 flex items-center gap-1">
                    <ArrowDownRight className="w-4 h-4" />
                    In: {activeOverview?.inflowRate || 48} pax/min
                  </span>
                  <span className="text-blue-700 flex items-center gap-1">
                    <ArrowUpRight className="w-4 h-4" />
                    Out: {activeOverview?.outflowRate || 45} pax/min
                  </span>
                </div>
              </div>

              <div className="p-3.5 sm:p-4 rounded-2xl bg-white border border-[#E5DED0] shadow-sm space-y-1">
                <span className="text-[10px] sm:text-[11px] text-gray-500 font-semibold block uppercase">Estimated Queue Length</span>
                <strong className="text-xs sm:text-sm font-bold text-[#102A56] block">
                  {activeOverview?.queueLengthMeters || 180} Meters
                </strong>
              </div>

              <div className="p-3.5 sm:p-4 rounded-2xl bg-white border border-[#E5DED0] shadow-sm space-y-1">
                <span className="text-[10px] sm:text-[11px] text-gray-500 font-semibold block uppercase">Recommended Visiting Window</span>
                <strong className="text-xs font-bold text-[#0D8259] block truncate">
                  {activeOverview?.recommendedWindow || "01:30 PM - 03:45 PM (~15m wait)"}
                </strong>
              </div>
            </div>
          </div>
        )}

        {/* Zone Map and Live CCTV Preview */}
        {selectedTemple && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8">
            <ZoneCongestionMap zones={selectedTemple.zones} templeName={selectedTemple.name} />
            <SimulatedCCTVStream cams={selectedTemple.cctvCams} templeName={selectedTemple.name} />
          </div>
        )}

        {/* Hourly Crowd Surge Forecast Chart */}
        <div className="bg-white rounded-3xl border border-[#E5DED0] p-4 sm:p-8 shadow-luxury space-y-4 sm:space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1.5 sm:gap-2 pb-3 sm:pb-4 border-b border-[#EBE4D5]">
            <div>
              <span className="text-[10px] sm:text-[11px] font-bold uppercase tracking-widest text-[#E97820]">
                AI Predictive Models (Simulated)
              </span>
              <h3 className="font-serif text-xl sm:text-2xl font-bold text-[#102A56]">
                24-Hour Crowd Inflow & Peak Forecast
              </h3>
            </div>
            <span className="text-[11px] sm:text-xs text-gray-500 font-medium">Model: Gradient Boosted Spatial Regression</span>
          </div>

          <div className="h-72 sm:h-80 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={crowdData?.hourlyPredictions || []} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F0EBE1" />
                <XAxis dataKey="hour" stroke="#64748B" fontSize={11} />
                <YAxis stroke="#64748B" fontSize={11} unit="%" />
                <Tooltip
                  contentStyle={{ backgroundColor: '#102A56', color: '#fff', borderRadius: '12px', border: 'none' }}
                />
                <Legend wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
                <Line type="monotone" dataKey="somnath" name="Somnath" stroke="#102A56" strokeWidth={3} dot={{ r: 3 }} />
                <Line type="monotone" dataKey="dwarka" name="Dwarka" stroke="#E97820" strokeWidth={3} dot={{ r: 3 }} />
                <Line type="monotone" dataKey="ambaji" name="Ambaji" stroke="#0D8259" strokeWidth={2} dot={{ r: 2 }} />
                <Line type="monotone" dataKey="pavagadh" name="Pavagadh" stroke="#D5A63A" strokeWidth={2} dot={{ r: 2 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Critical Zones List & AI Recommendations */}
        <div className="bg-white rounded-3xl border border-[#E5DED0] p-6 sm:p-8 shadow-luxury space-y-6">
          <div className="flex items-center justify-between pb-3 border-b border-[#EBE4D5]">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-[#E97820]" />
              <h3 className="font-serif text-xl font-bold text-[#102A56]">
                Monitored Chokepoints & Flow Advisories
              </h3>
            </div>
            <span className="text-xs bg-amber-50 text-amber-800 border border-amber-200 px-3 py-1 rounded-full font-bold">
              {crowdData?.criticalZonesList?.length || 2} Active Monitored Corridors
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {(crowdData?.criticalZonesList || []).map((cz) => (
              <div
                key={cz.id}
                className="p-4 rounded-2xl bg-[#FAF8F5] border border-[#EBE4D5] space-y-2.5"
              >
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-[#E97820]">
                    {cz.templeName}
                  </span>
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700">
                    {cz.severity}
                  </span>
                </div>
                <h5 className="font-bold text-xs sm:text-sm text-[#102A56]">
                  {cz.zoneName}
                </h5>
                <p className="text-xs text-slate-600 leading-relaxed">
                  {cz.actionRecommended}
                </p>
                <div className="text-[11px] text-gray-500 pt-1 border-t border-gray-200">
                  Density: <strong className="text-red-600">{cz.currentDensity}</strong> (Threshold: {cz.threshold})
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
