import { CrowdSnapshot } from "../models/CrowdSnapshot.js";
import { isDatabaseConnected } from "../config/db.js";
import { alertService } from "./alertService.js";

/**
 * 🛕 Real-time Crowd Simulation & Predictive Intelligence Engine
 * Target Pilgrimage Shrines: Somnath, Dwarka, Ambaji, Pavagadh
 * Note: Clearly labeled as "Simulation / Demo Telemetry".
 */

// Master Temple Simulation Models
const TEMPLE_SIM_PROFILES = {
  somnath: {
    id: "somnath",
    name: "Shree Somnath Jyotirlinga",
    shortName: "Somnath",
    maxCapacity: 25000,
    baseWaitFactor: 0.45,
    zones: [
      { id: "som-z1", name: "Sabhamandap Central Aisle", density: 54, threshold: 75, flowRate: 48, cctvNode: "CCTV-SOM-01" },
      { id: "som-z2", name: "Arabian Sea Promenade Queue", density: 62, threshold: 70, flowRate: 52, cctvNode: "CCTV-SOM-04" },
      { id: "som-z3", name: "Garbhagriha Inner Sanctum Altar", density: 68, threshold: 80, flowRate: 45, cctvNode: "CCTV-SOM-07" },
      { id: "som-z4", name: "North Exit Corridor", density: 38, threshold: 85, flowRate: 50, cctvNode: "CCTV-SOM-12" },
    ],
  },
  dwarka: {
    id: "dwarka",
    name: "Shree Dwarkadhish Temple",
    shortName: "Dwarkadhish",
    maxCapacity: 28000,
    baseWaitFactor: 0.65,
    zones: [
      { id: "dwr-z1", name: "Moksha Dwaar (Gate 1 Inflow)", density: 82, threshold: 75, flowRate: 64, cctvNode: "CCTV-DWR-02" },
      { id: "dwr-z2", name: "Swarga Dwaar Sanctum Plaza", density: 78, threshold: 70, flowRate: 58, cctvNode: "CCTV-DWR-05" },
      { id: "dwr-z3", name: "Gomti Ghat Holding Deck", density: 45, threshold: 80, flowRate: 40, cctvNode: "CCTV-DWR-09" },
      { id: "dwr-z4", name: "Chappan Sidi Stairway", density: 70, threshold: 75, flowRate: 55, cctvNode: "CCTV-DWR-14" },
    ],
  },
  ambaji: {
    id: "ambaji",
    name: "Shree Ambaji Shaktipeeth",
    shortName: "Ambaji",
    maxCapacity: 35000,
    baseWaitFactor: 0.35,
    zones: [
      { id: "amb-z1", name: "Chachar Chowk Main Courtyard", density: 36, threshold: 70, flowRate: 35, cctvNode: "CCTV-AMB-01" },
      { id: "amb-z2", name: "Golden Sanctum Inner Queue", density: 42, threshold: 75, flowRate: 32, cctvNode: "CCTV-AMB-03" },
      { id: "amb-z3", name: "Gabbar Hill Base Corridor", density: 28, threshold: 80, flowRate: 25, cctvNode: "CCTV-AMB-08" },
      { id: "amb-z4", name: "VIP Darshan Passage", density: 22, threshold: 85, flowRate: 18, cctvNode: "CCTV-AMB-11" },
    ],
  },
  pavagadh: {
    id: "pavagadh",
    name: "Shree Pavagadh Mahakali",
    shortName: "Pavagadh",
    maxCapacity: 22000,
    baseWaitFactor: 0.58,
    zones: [
      { id: "pvg-z1", name: "Machi Base Ropeway Station", density: 68, threshold: 75, flowRate: 42, cctvNode: "CCTV-PVG-01" },
      { id: "pvg-z2", name: "Summit Upper Ropeway Deck", density: 84, threshold: 75, flowRate: 40, cctvNode: "CCTV-PVG-06" },
      { id: "pvg-z3", name: "Hilltop Staircase Pinchpoint", density: 76, threshold: 70, flowRate: 36, cctvNode: "CCTV-PVG-09" },
      { id: "pvg-z4", name: "Mahakali Mata Sanctum Enclosure", density: 72, threshold: 80, flowRate: 38, cctvNode: "CCTV-PVG-15" },
    ],
  },
};

// Hourly historical & prediction curve
const GENERATED_HOURLY_CHART = [
  { hour: "05:00 AM", somnath: 22, dwarka: 28, ambaji: 15, pavagadh: 20, overall: 21 },
  { hour: "06:30 AM", somnath: 48, dwarka: 56, ambaji: 25, pavagadh: 42, overall: 43 },
  { hour: "08:00 AM", somnath: 64, dwarka: 78, ambaji: 38, pavagadh: 68, overall: 62 },
  { hour: "10:00 AM", somnath: 72, dwarka: 85, ambaji: 46, pavagadh: 80, overall: 71 },
  { hour: "12:00 PM", somnath: 58, dwarka: 74, ambaji: 34, pavagadh: 60, overall: 57 },
  { hour: "02:00 PM", somnath: 35, dwarka: 45, ambaji: 20, pavagadh: 38, overall: 35 },
  { hour: "04:30 PM", somnath: 60, dwarka: 72, ambaji: 40, pavagadh: 66, overall: 60 },
  { hour: "06:30 PM", somnath: 82, dwarka: 88, ambaji: 52, pavagadh: 78, overall: 75 },
  { hour: "08:00 PM", somnath: 68, dwarka: 75, ambaji: 42, pavagadh: 55, overall: 60 },
  { hour: "09:30 PM", somnath: 30, dwarka: 36, ambaji: 18, pavagadh: 24, overall: 27 },
];

// Live telemetry state in memory
let telemetryState = {
  dataSource: "Simulation / Demo Telemetry",
  telemetryType: "Simulated Edge Computer Vision & Turnstile Sensor Telemetry",
  notice: "All telemetry values are generated by the DivYatra AI Simulation Engine for operational planning and demonstration.",
  lastUpdated: new Date().toISOString(),
  totalActivePilgrims: 15620,
  averageWaitTimeMinutes: 34,
  activeCriticalZones: 2,
  systemAlertLevel: "ELEVATED_WATCH",
  hourlyPredictions: GENERATED_HOURLY_CHART,
  templeOverview: [],
  criticalZonesList: [],
};

/**
 * Recalculate and simulate dynamic crowd drift with predictive logic
 */
export const runSimulationCycle = () => {
  const overviews = [];
  const criticalZones = [];

  Object.values(TEMPLE_SIM_PROFILES).forEach((profile) => {
    // 1. Dynamic Inflow / Outflow drift
    const inflowDelta = Math.floor((Math.random() - 0.48) * 8);
    const outflowDelta = Math.floor((Math.random() - 0.48) * 6);

    const baseInflow = profile.id === "dwarka" ? 64 : profile.id === "pavagadh" ? 52 : profile.id === "somnath" ? 48 : 34;
    const baseOutflow = profile.id === "dwarka" ? 56 : profile.id === "pavagadh" ? 46 : profile.id === "somnath" ? 47 : 36;

    const inflowRate = Math.max(15, baseInflow + inflowDelta);
    const outflowRate = Math.max(12, baseOutflow + outflowDelta);

    // 2. Predictive trend computation
    let trend = "stable";
    let predictionSummary = "Flow is balanced and stable.";
    if (inflowRate > outflowRate + 4) {
      trend = "rising";
      predictionSummary = `Inflow (${inflowRate} pax/min) exceeds Outflow (${outflowRate} pax/min). Anticipating +15% queue build-up in next 30 mins.`;
    } else if (outflowRate > inflowRate + 4) {
      trend = "falling";
      predictionSummary = `Outflow (${outflowRate} pax/min) exceeds Inflow (${inflowRate} pax/min). Queue easing steadily.`;
    }

    // 3. Occupancy calculation
    const baseOccupancy = profile.id === "dwarka" ? 79 : profile.id === "pavagadh" ? 74 : profile.id === "somnath" ? 58 : 34;
    const occupancy = Math.min(95, Math.max(15, baseOccupancy + Math.floor((Math.random() - 0.45) * 5)));
    const activeCount = Math.round((occupancy / 100) * profile.maxCapacity * 0.28);
    const avgWait = Math.max(5, Math.round(occupancy * profile.baseWaitFactor));
    const queueLengthMeters = Math.round((activeCount * 0.12) + (occupancy * 1.5));

    // 4. Congestion status
    let status = "optimal";
    let statusLabel = "Optimal Flow";
    let statusColor = "emerald";

    if (occupancy >= 80) {
      status = "critical";
      statusLabel = "Critical Surge - Divert General Queue";
      statusColor = "red";
    } else if (occupancy >= 70) {
      status = "congested";
      statusLabel = "High Congestion - Queues Active";
      statusColor = "amber";
    } else if (occupancy >= 45) {
      status = "moderate";
      statusLabel = "Moderate Density";
      statusColor = "blue";
    }

    // 5. Zone simulation
    const simulatedZones = profile.zones.map((z) => {
      const zoneDrift = Math.floor((Math.random() - 0.48) * 4);
      const density = Math.min(96, Math.max(20, z.density + zoneDrift));
      const isExceeded = density >= z.threshold;

      if (isExceeded) {
        criticalZones.push({
          id: `cz-${z.id}`,
          templeId: profile.id,
          templeName: profile.name,
          zoneName: z.name,
          currentDensity: `${density}%`,
          threshold: `${z.threshold}%`,
          severity: density > 80 ? "CRITICAL" : "WARNING",
          actionRecommended: `Adjust turnstile inflow rate at ${z.name} and mobilize zone marshals.`,
          cctvNode: z.cctvNode,
        });
      }

      return {
        id: z.id,
        name: z.name,
        currentDensity: density,
        threshold: z.threshold,
        flowRatePerMinute: z.flowRate + Math.floor((Math.random() - 0.5) * 6),
        status: isExceeded ? "CONGESTED" : "NORMAL",
        cctvNode: z.cctvNode,
      };
    });

    // 6. Optimal visiting recommendation
    const recommendedWindow =
      occupancy > 65
        ? "01:30 PM - 03:45 PM (Estimated wait: ~12-15 mins)"
        : "Current window is highly favorable for Darshan.";

    overviews.push({
      templeId: profile.id,
      name: profile.name,
      shortName: profile.shortName,
      crowdPercentage: occupancy,
      status,
      statusLabel,
      statusColor,
      activeCount,
      avgWait,
      queueLengthMeters,
      inflowRate,
      outflowRate,
      trend,
      predictionSummary,
      recommendedWindow,
      zones: simulatedZones,
      criticalZonesCount: simulatedZones.filter((z) => z.currentDensity >= z.threshold).length,
      lastSimulated: new Date().toISOString(),
      dataSource: "Simulation / Demo Telemetry",
    });
  });

  telemetryState.templeOverview = overviews;
  telemetryState.criticalZonesList = criticalZones;
  telemetryState.totalActivePilgrims = overviews.reduce((s, t) => s + t.activeCount, 0);
  telemetryState.averageWaitTimeMinutes = Math.round(
    overviews.reduce((s, t) => s + t.avgWait, 0) / overviews.length
  );
  telemetryState.activeCriticalZones = criticalZones.length;
  telemetryState.lastUpdated = new Date().toISOString();

  return telemetryState;
};

// Initial simulation pulse
runSimulationCycle();

// Background Autonomous Simulation Cycle every 8 seconds
setInterval(() => {
  runSimulationCycle();
}, 8000);

export const crowdService = {
  /**
   * Get complete aggregate crowd intelligence telemetry
   */
  async getLiveCrowd() {
    return telemetryState;
  },

  /**
   * Get specific temple crowd metrics & computer vision simulation breakdown
   */
  async getCrowdByTempleId(templeId) {
    if (!templeId) return null;
    const cleanId = templeId.toLowerCase();
    const overview = telemetryState.templeOverview.find(
      (t) => t.templeId.toLowerCase() === cleanId
    );

    if (!overview) {
      return telemetryState.templeOverview[0];
    }

    return {
      ...overview,
      hourlyTrend: GENERATED_HOURLY_CHART.map((h) => ({
        hour: h.hour,
        density: h[cleanId] || h.overall,
      })),
      dataSource: "Simulation / Demo Telemetry",
      notice: "Simulation / Demo Telemetry — Not live CCTV video streaming.",
    };
  },

  /**
   * Future-proof edge OpenCV/YOLO inference ingestion hook
   * Allows external Python AI microservice to push edge detection metrics
   */
  async ingestEdgeTelemetry(telemetryPayload) {
    const { templeId, zoneId, density, headcount } = telemetryPayload;
    console.log(`📡 [Edge Ingestion] Received AI inference telemetry for ${templeId}/${zoneId}: ${headcount} pax (${density}%)`);
    return { success: true, timestamp: new Date().toISOString() };
  },

  /**
   * Trigger immediate recalculation simulation pulse
   */
  async triggerSimulationPulse() {
    return runSimulationCycle();
  },
};
